# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-21 16:43
from __future__ import unicode_literals

import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(help_text='A unique name used for reference in the templates', max_length=255, unique=True, verbose_name='slug')),
                ('content', models.TextField(blank=True, null=True, verbose_name='content')),
                ('sites', models.ManyToManyField(default=[1], to='sites.Site')),
            ],
            options={
                'ordering': ('slug',),
                'verbose_name_plural': 'snippets',
                'verbose_name': 'snippet',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager('sites')),
            ],
        ),
    ]
